// English text for the case pool. Same order as POOL in cases.js; only text lives here — tiers,
// verdicts, evidence flags and scenes come from POOL, so both languages play by the same rules.
// Fields left out (URLs, handles, proper names) are taken from the Polish case unchanged.
// The story stays set in Poland on purpose: the places are part of the game's world.

const POOL_EN = [
  // ---------- tier 1: source and date ----------
  { reporter: 'A reader from Toruń',
    article: { headline: 'BREAKING: Petrol and diesel cars banned from cities over 50,000 from Monday',
      author: 'Editorial staff', date: '5 Oct 2026, 0:14',
      lead: 'The government quietly passed the regulation. The fine will be 5,000 zł. Share before they delete it!' },
    ev: { zrodlo: 'The domain gazeta-nadwislanska.info was registered 9 days ago by a hidden owner. The real Gazeta Nadwiślańska has run at gazetanadwislanska.pl since 1998 and never published this story.',
          data: 'First seen 4 Oct 2026, 23:58. No official journal contains any such regulation.' },
    lesson: 'A spoofed domain. Read the address letter by letter: fake sites pose as well-known titles. “Share before they delete it” is a classic hook.' },

  { reporter: 'A driver from Sieradz',
    article: { headline: 'Lipowa Street bridge in Sieradz closed from 14 October',
      date: '5 Oct 2026, 7:40',
      lead: 'The city roads authority announces a three-week repair. The detour will run along Kościuszki and Polna streets, and bus lines 3 and 7 will change routes.' },
    ev: { zrodlo: 'The site has run since 1998, with the editor-in-chief and newsroom address in the footer. The author has had a byline here for 6 years.',
          data: 'Published today, 7:40. The same notice is on the city roads authority’s website, dated 2 Oct 2026.' },
    lesson: 'A known source, a named author, and the institution itself confirms it. Specific, boring news is usually true.' },

  { reporter: 'A worried dad',
    post: { name: 'Health Without Secrets', time: '3 h',
      text: 'Lemon juice with baking soda cures flu in 24 hours! Big Pharma doesn’t want you to know. Doctors stay silent!!!',
      shares: '42K' },
    ev: { zrodlo: 'A page with no author and no contact details. The link in its profile leads to a supplement shop.',
          data: 'The same text has circulated since 2017 in several languages, each time as a “new discovery”.' },
    lesson: 'A miracle cure, a common enemy (Big Pharma, doctors) and a shop in the background. When someone profits from what you believe, check twice.' },

  { reporter: 'A student from Lublin',
    post: { name: 'News Right Now', time: '25 min',
      text: 'Happening NOW! Central Zamość is under water. Where are the emergency services?!',
      shares: '9.1K',
      link: { title: 'Downpour floods central Zamość. Knee-deep water on the Great Market Square' } },
    ev: { zrodlo: 'Radio Wschód is a regional station on air since 1994. The @InfoNaJuz account mostly reshares other people’s content with its own comment.',
          data: 'The article in the station’s archive is dated 14 Jul 2019. Today Zamość has clear skies and no rain.' },
    lesson: 'Real news from years ago passed off as today’s. Check the publication date, not the date it was shared.' },

  { reporter: 'A pupil from Sieradz',
    article: { outlet: 'MPK Sieradz · notice',
      headline: 'From 1 November, a monthly pass for pupils costs 1 zł',
      author: 'Passenger service', date: '5 Oct 2026, 9:00',
      lead: 'The city council passed a resolution setting a symbolic price for the monthly pass for primary and secondary school pupils. It can be bought in the app and at service points.' },
    ev: { zrodlo: 'The official site of the city transport company, on the city’s own domain. Same contact details since 2009.',
          data: 'The city council resolution of 24 Sep 2026 is published in the Public Information Bulletin, the official register of local government decisions.' },
    lesson: 'Good news doesn’t have to be fake. An official source and a document in the public register settle it.' },

  { reporter: 'A mum of two pupils',
    post: { name: 'Mazovia Parents', time: '50 min',
      text: 'From tomorrow ALL schools in the province switch to remote learning! The education board confirms. Pass it on!',
      shares: '21K',
      link: { title: 'Education board: remote learning in every school in the province from tomorrow' } },
    ev: { zrodlo: 'Echo Regionu is a news site running since 2005. The @RodziceMazowsza group has 80,000 members and does not check posts.',
          data: 'The Echo Regionu article is dated 11 Mar 2020, the first days of the pandemic. The education board has issued no notice today.' },
    lesson: 'An old article about a real event, back as if it were today’s. The link looks credible, but the publication date says it all.' },

  { reporter: 'A volunteer',
    article: { headline: 'Food bank collection in 40 shops across the region on Saturday',
      date: '5 Oct 2026, 8:10',
      lead: 'Volunteers in yellow vests will collect long-life products. Donations go to soup kitchens and shelters for single mothers.' },
    ev: { zrodlo: 'The site has run since 1998. The author has covered social issues for 4 years.',
          data: 'Published today. The organiser’s website gives the same date and list of shops.' },
    lesson: 'A calm tone, specific places and dates, confirmed by the organiser. This is what real announcements look like.' },

  { reporter: 'A pensioner from Radom',
    post: { name: 'Energy Allowance 2026', time: '4 h',
      text: 'The government is paying an 800 zł energy allowance to every household! Apply by Friday: dodatek-energia-gov.pl.com. You only need your online banking login.',
      shares: '12K' },
    ev: { zrodlo: 'The domain dodatek-energia-gov.pl.com was registered abroad 2 days ago. The .pl.com ending has nothing to do with government sites (those end in .gov.pl), and despite “gov” in its name the profile is not official.',
          data: 'Posted today. Similar “allowances” appeared in 2022 and 2024, each time linking to a different domain.' },
    lesson: 'Phishing dressed up as a government office. No institution asks for your banking login through a form in a post. Check the ending: .pl.com is not .gov.pl.' },

  { reporter: 'A TV series fan',
    article: { headline: 'Jan Wiatrowski has died. The star of “House on the Warta” was 58',
      author: 'Editorial staff', date: '5 Oct 2026, 6:02',
      lead: 'Sad news has spread across the country. The family asks for privacy. Details in the gallery below.' },
    ev: { zrodlo: 'The site was set up a month ago and has no editorial footer. The page carries 14 ads and five redirects.',
          data: 'An hour ago the actor posted a photo from the set on his own profile, captioned “Alive and well, again.”' },
    lesson: 'A fake death notice is classic clickbait. Before you post condolences, check the person’s official accounts and established media.' },

  { reporter: 'A resident of Słoneczne estate',
    article: { outlet: 'Central Grid Company · notice',
      headline: 'Planned power cut: Słoneczne estate, Friday 9 October, 8:00–14:00',
      author: 'Communications team', date: '5 Oct 2026, 7:30',
      lead: 'The cause is upgrade work at the transformer station on Akacjowa Street. Please charge your devices in advance.' },
    ev: { zrodlo: 'The official site of the grid operator. Same address and helpline since 2011.',
          data: 'Published today, with the advance notice the law requires. The local paper carries the same notice.' },
    lesson: 'A dry notice on an official site, with a specific date, time and reason. Nothing here plays on emotions.' },

  // ---------- tier 2: photos ----------
  { reporter: 'A pensioner from Kielce',
    post: { name: 'Drivers of Poland', time: '1 h',
      text: 'This is what petrol stations look like TODAY all over the country! Fuel is about to run out, fill up while you can!!!',
      shares: '27K' },
    photo: { caption: 'a mile-long queue of cars at the pumps' },
    ev: { zrodlo: 'Account created in 2023. Posts mostly alarming content about fuel prices.',
          data: 'Posted today, 8:15. Local stations report no shortages.',
          obraz: 'The photo was first published by a foreign news site on 3 Mar 2022. It shows a station in another country — the prices on the sign are in a foreign currency.' },
    lesson: 'A real photo in a false context. A reverse image search shows within seconds where it really comes from. A call to panic (“fill up!”) is a red flag.' },

  { reporter: 'A mum from Kraków',
    post: { name: 'Kraków News 24', time: '40 min',
      text: 'WARNING! A wolf on the playground by the Planty park! Keep your kids indoors!',
      shares: '15K' },
    photo: { caption: 'a wolf on a playground by the swings' },
    ev: { zrodlo: 'Account created 3 weeks ago and, despite its name, not linked to any newsroom. 40,000 followers arrived in a single week.',
          data: 'Posted today, 10:20. The city guard has issued no statement.',
          obraz: 'No earlier appearances of the image. Analysis points to an AI-generated picture: the swing’s chain grows into the tree, and the wolf’s reflection in the puddle has five legs.' },
    lesson: 'An AI-generated image. Look for errors in the details (hands, lettering, reflections) and check whether anyone else confirms the event.' },

  { reporter: 'A bus driver',
    article: { headline: '20 new electric buses hit the streets of Lublin',
      date: '6 Oct 2026, 10:02',
      lead: 'The buses will run on lines 18 and 25 to start with. Three quarters of the cost was covered by EU funds.' },
    photo: { caption: 'a row of new buses at the depot' },
    ev: { zrodlo: 'A local news site running since 2011, with editors and authors listed in the footer.',
          data: 'Published today, 10:02.',
          obraz: 'The photo appeared this morning on the city transport company’s website, credited to a named photographer.' },
    lesson: 'Everything checks out: a local source, today’s date and a photo from the operator’s official site.' },

  { reporter: 'A civics teacher',
    post: { name: 'Marek the Patriot', time: '2 h',
      text: 'OUTRAGE!!! This has never happened before. Share it, people need to know!',
      shares: '6.3K',
      link: { title: 'Parliament abolishes Mondays. The working week will start on Tuesday' } },
    photo: { caption: 'MPs voting in the main chamber' },
    ev: { zrodlo: 'Szyderca.pl is a satirical site. Its footer says: “All articles are fiction and jokes.”',
          data: 'The article was published on 1 Apr 2026.',
          obraz: 'A photo from the chamber taken in 2024, used as an illustration.' },
    lesson: 'Satire taken seriously. Before you get outraged, check what the source site is and whether the story is from 1 April.' },

  { reporter: 'A Widzew resident',
    article: { headline: 'Warehouse fire in Widzew. No one injured',
      date: '6 Oct 2026, 6:50 (upd. 9:10)',
      lead: 'The fire broke out before dawn. Twelve fire crews worked at the scene. Residents were asked to keep their windows shut.' },
    photo: { caption: 'clouds of smoke over a warehouse' },
    ev: { zrodlo: 'The site has run since 2014. The author has covered events in the region for years.',
          data: 'Published today at 6:50, updated at 9:10.',
          obraz: 'The photo was posted today at 6:30 by the local fire station on its own profile.' },
    lesson: 'Fast but reliable reporting: an updated article, an official photo from the emergency services and a named author.' },

  { reporter: 'A student from Wrocław',
    post: { name: 'Voice of the People', time: '3 h',
      text: 'Half a million people on the streets of Warsaw yesterday! The media are silent, but photos don’t lie.',
      shares: '38K' },
    photo: { caption: 'a crowd with flags on a wide street' },
    ev: { zrodlo: 'The account has existed since 2020 and posts political content from various sources.',
          data: 'A registered demonstration did take place in Warsaw yesterday. Police estimate 3,000 participants.',
          obraz: 'The photo is from the final night of a music festival in another city, published on 28 Jun 2019 by a photo agency.' },
    lesson: 'A real event, someone else’s photo. A picture from another place and time is meant to show a scale that never happened.' },

  { reporter: 'An angler near Płock',
    post: { name: 'Mazovia Alert', time: '1 h',
      text: 'A SHARK IN THE VISTULA near Płock!!! Anglers are fleeing the bank. Nobody is saying where it came from!',
      shares: '64K' },
    photo: { caption: 'a shark fin breaking the river surface by a bridge' },
    ev: { zrodlo: 'Account created a week ago. Every post is a sensation with no sources.',
          data: 'Posted today. No emergency service or local outlet reports anything.',
          obraz: 'A photomontage: the fin comes from a 2015 photo taken in Australia, the bridge from a stock photo of Płock. The fin’s shadow falls the opposite way to the shadows of the bridge piers.' },
    lesson: 'A photomontage. Reverse image search finds both sources, and a careful eye sees shadows falling in different directions.' },

  { reporter: 'A tourist from Gdańsk',
    article: { headline: 'First snow in Zakopane. 15 cm on Kasprowy Wierch',
      date: '6 Oct 2026, 7:45',
      lead: 'Overnight the temperature dropped below zero. Mountain rescuers warn of icy trails above 1,500 m.' },
    photo: { caption: 'snowy roofs and peaks in the morning' },
    ev: { zrodlo: 'A regional site running since 2009, author named.',
          data: 'Published today, 7:45. The weather station on Kasprowy Wierch records −3°C and snowfall.',
          obraz: 'The photo is a frame from today’s recording of a public webcam in Zakopane, 7:12.' },
    lesson: 'Snow in October sounds odd, but in the Tatras it’s normal. Unusual doesn’t mean false: weather data and the webcam confirm it.' },

  { reporter: 'A local councillor',
    post: { name: 'Kraków No Spin', time: '2 h',
      text: 'This is the park after yesterday’s city festival. Paid for with our taxes!',
      shares: '8.7K' },
    photo: { caption: 'a lawn strewn with rubbish and bottles' },
    ev: { zrodlo: 'An account run by local activists since 2021, often critical of the city authorities.',
          data: 'The festival in the park did take place yesterday. Cleaning crews worked until midnight.',
          obraz: 'The photo was published by a site in another city on 12 Aug 2021, after an illegal party. It does not show this park.' },
    lesson: 'A real event, but a photo from another situation. Even fair criticism loses credibility when it leans on someone else’s picture.' },

  { reporter: 'A taxi driver',
    post: { name: 'Last Minute', time: '35 min',
      text: 'They just showed it on TV! Nationwide curfew from Saturday!!!',
      shares: '47K' },
    photo: { caption: 'screenshot: a BREAKING banner on a news channel' },
    ev: { zrodlo: 'An anonymous account created this month.',
          data: 'No station broadcast this today; it is not in any programme archive.',
          obraz: 'The screenshot is not in any TV archive. A free “fake news” meme generator offers the exact same banner layout.' },
    lesson: 'A doctored screenshot. A BREAKING banner takes a minute to make in a meme generator. Look for the footage on the station’s own website.' },

  // ---------- tier 3: documents ----------
  { reporter: 'A nurse from Gdańsk',
    post: { name: 'Politics Uncensored', time: '1 h',
      text: 'Health minister: “Vaccinating children makes no sense.” They admitted it themselves!',
      shares: '33K' },
    photo: { caption: 'graphic: the minister’s photo and a quote on a red background' },
    ev: { zrodlo: 'An anonymous account. Posts quote graphics with no links to sources.',
          data: 'The graphic is from today. The interview it quotes was broadcast on the radio on 2 Oct 2026.',
          obraz: 'The minister’s photo comes from the ministry’s official gallery.',
          dokument: 'Full interview transcript: “Saying that vaccinating children makes no sense is a harmful myth we are fighting.”' },
    lesson: 'A quote cut out of context so it means the opposite. A quote graphic is not a source. Find the full statement.' },

  { reporter: 'A barista from Poznań',
    article: { outlet: 'Health Today',
      headline: 'Scientists warn: coffee doubles your risk of heart attack!',
      author: 'Editorial staff', date: '7 Oct 2026, 8:30',
      lead: 'A new study leaves no doubt. If you drink coffee every day, read this right now.' },
    photo: { caption: 'a cup of coffee on a table' },
    ev: { zrodlo: 'The site has existed since 2015 and lives off ads. Its headlines often read “scientists warn”.',
          data: 'The study was published in a scientific journal a week ago.',
          obraz: 'A stock photo.',
          dokument: 'The study was done on 24 mice given caffeine at a dose equal to about 60 cups a day for a human. The authors write: “the results should not be extrapolated to humans”.' },
    lesson: 'The headline twists a real study. Who was studied, how many, at what dose? The answers are in the paper, not the title.' },

  { reporter: 'A farmer near Płock',
    article: { headline: 'September 2026 the warmest on record in Poland',
      date: '7 Oct 2026, 11:15',
      lead: 'The month’s average temperature was 17.9°C, the highest since regular measurements began in 1951.' },
    photo: { caption: 'chart of average September temperatures, 1951–2026' },
    ev: { zrodlo: 'The site has run since 1998. The author specialises in climate.',
          data: 'Published today, 11:15.',
          obraz: 'The chart comes from the monthly report of the national weather service.',
          dokument: 'Monthly report: average September temperature 17.9°C, the highest since 1951. The figures in the article match the report.' },
    lesson: 'The numbers in the article match the source document. This is what reliable journalism looks like.' },

  { reporter: 'A gaming fan, age 13',
    post: { time: '12 min',
      text: 'Giving away 500 smartphones to celebrate 5M subs!!! Click the link and enter your card details to pay 9.99 zł shipping. Until midnight only!',
      shares: '51K' },
    photo: { caption: 'a pile of new smartphones in boxes' },
    ev: { zrodlo: 'The account @kubagra_offical (note the typo) was created 3 days ago. The real creator’s account is @kubagra, with a verification badge.',
          data: 'Posted today. Identical “giveaways” appeared this month in the name of four other creators.',
          obraz: 'The phone photo is a stock image.',
          dokument: 'There is no word of a contest on the creator’s real channel. The form collects payment card details.' },
    lesson: 'A phishing scam. A typo in the account name, time pressure and a request for card details: three red flags at once.' },

  { reporter: 'A head teacher',
    article: { outlet: 'Daily Online Gazette',
      headline: 'Report: 70% of Polish pupils do not understand what they read',
      author: 'no byline', date: '7 Oct 2026, 7:05',
      lead: 'According to the latest report by the Institute for Educational Research, the situation is dramatic. Experts are sounding the alarm.' },
    ev: { zrodlo: 'The site has existed for a year, with no names in its editorial footer.',
          data: 'Published today; a dozen sites reprinted it within an hour.',
          dokument: 'The institute published no such report. In its latest study the share of pupils with serious reading difficulties was 17%.' },
    lesson: 'A made-up figure pinned to a serious-sounding institution. If the article doesn’t link to the report, find it yourself.' },

  { reporter: 'A teenager’s parent',
    article: { headline: 'Scientists confirm: video games raise IQ by 20 points',
      date: '7 Oct 2026, 9:20',
      lead: 'Daily gaming is a workout for the brain. The results surprised even the authors.' },
    photo: { caption: 'a game controller in front of a screen' },
    ev: { zrodlo: 'A gaming site running since 2017, funded by ads from game publishers.',
          data: 'The study was published in a scientific journal 3 days ago.',
          obraz: 'A stock photo.',
          dokument: 'The study involved 40 adults. After 6 weeks of gaming, their score on one working-memory test improved by 4%. The paper does not mention IQ at all.' },
    lesson: 'A small effect on one test grew into “20 IQ points” in the headline. Compare the numbers in the title with the numbers in the study.' },

  { reporter: 'A school counsellor',
    article: { headline: 'Report: one in three pupils has faced online hate',
      date: '7 Oct 2026, 10:05',
      lead: 'The survey covered 4,200 pupils from 60 schools. The hate most often targeted appearance and origin.' },
    ev: { zrodlo: 'The site has run since 1998; the author specialises in education.',
          data: 'Published today, a day after the report came out.',
          dokument: 'Report of the pupils’ rights ombudsman, p. 14: 34% of respondents faced online hate within a year. Sample and method are described in the appendix.' },
    lesson: 'The figures in the article match the report, and the report explains its method. This is how to cite research properly.' },

  { reporter: 'A secondary school student',
    post: { name: 'Wise Quotes', time: '5 h',
      text: '“Whoever reads the news only online knows less than one who reads none at all.” — Prof. Zbigniew Halicki, Nobel laureate',
      shares: '19K' },
    photo: { caption: 'graphic: portrait of an elderly professor and a quote' },
    ev: { zrodlo: 'A motivational quotes page with 300,000 followers. It never gives sources.',
          data: 'The graphic has circulated since 2019, earlier attributed to a different name.',
          obraz: 'The portrait is a stock photo of a model, described in the photo bank as “elderly man with glasses”.',
          dokument: 'No one of that name appears on the list of Nobel laureates. The quote is not in any book or interview.' },
    lesson: 'An invented authority. A serious-sounding title and a portrait are there to lend the quote weight. Check whether the person exists at all.' },

  { reporter: 'A resident of Zielona Dolina',
    article: { headline: 'Crime in Zielona Dolina up 100%! Residents afraid to leave their homes',
      author: 'Editorial staff', date: '7 Oct 2026, 6:40',
      lead: 'The latest police figures leave no illusions. Is our municipality still safe?' },
    photo: { caption: 'a police car at night on an empty street' },
    ev: { zrodlo: 'A local site running for 2 years, with no names in the footer.',
          data: 'Police figures for the third quarter were published yesterday.',
          obraz: 'A stock photo, not from this municipality.',
          dokument: 'Police report: 4 bicycle thefts were reported in the third quarter, against 2 a year earlier. No other crimes were recorded. The municipality has 900 residents.' },
    lesson: 'Percentages of small numbers are the scariest. A “100% rise” here means two more bikes. Always ask: 100% of what?' },

  { reporter: 'A history teacher',
    post: { name: 'Atlas School Publishing', time: '1 h',
      text: 'We apologise for an error in the year 7 history textbook (p. 112, wrong date of a battle). The corrected version is already in the e-book, and schools will receive erratum stickers.',
      shares: '2.1K' },
    ev: { zrodlo: 'The publisher’s official, verified profile, active since 2012.',
          data: 'Posted today.',
          dokument: 'The erratum on the publisher’s website confirms the error and gives the correct date. Schools received the same notice.' },
    lesson: 'A correction is a sign of reliability, not weakness. The source admitted the error and showed how it is fixing it.' }
];

if (typeof module !== 'undefined') module.exports = { POOL_EN };
